server:
  port: 80

# yml规范
country: china
province: anhui
city: hefei

# 对象
# 创建类 用于封装以下的数据 由Spring帮我们去加载到对象中,并一定要告诉Spring加载这组信息(yml引用类型属性数据课程)
# 使用时直接从Spring直接获取信息
user:
  uname: zhangsan
  age: 21

# 数组
likes:
  - apple
  - banana
  - orange

# 对象数组
users:
  - name: zhangsan # 格式1
    age: 21
  -
    name: lisi # 格式2
    age: 22

baseDir: c:\windows
# 使用${属性名}的方式引用数据
tempDir: ${baseDir}\temp
tempDir2: "${baseDir}\temp" # 加引号则解析转义字符