print("             {@}")
print("          {@} * {@}")
print("       {@} * {@} * {@}")
print("    {@}* {@} * {@} * {@}")
print("     \\ {@} * {@} * {@} /")
print("        \\ \\ \\ l / / /")
print("         \\\\ \\ Y / //")
print("           \\\\ l //")
print("            \\\\Y// ")
print("              >=<  ")
print("            //*\\\\ ")
